nameOverride: ""
fullnameOverride: ""

global:
  gitProvider: github
  dnsWildCard: eks-sandbox.aws.main.edp.projects.epam.com

github:
  # -- The GitHub host, adjust this if you run a GitHub enterprise. Default: github.com
  host: github.com
  webhook:
    # -- Existing secret which holds GitHub integration credentials: Username, Access Token, Secret String and Private SSH Key
    existingSecret: github
