nameOverride: ""
fullnameOverride: ""

global:
  gitProvider: github
  dnsWildCard: ""
  gerritSSHPort: "30003"

github:
  # -- The GitHub host, adjust this if you run a GitHub enterprise. Default: github.com
  host: github.com
  webhook:
    # -- Existing secret which holds GitHub integration credentials: Username, Access Token, Secret String and Private SSH Key
    existingSecret: github

gitlab:
  # -- The GitLab host, adjust this if you run a GitLab enterprise. Default: gitlab.com
  host: git.epam.com
  webhook:
    # -- Existing secret which holds GitLab integration credentials: Username, Access Token, Secret String and Private SSH Key
    existingSecret: gitlab
